version: '3.7'

services:
  drone-server:
    image: drone/drone:2
    ports:
      - 80:80
      - 443:443
    volumes:
      - drone_server_data:/var/lib/drone
      - drone_server_certs:/certs
    restart: always
    environment:
      DRONE_SERVER_HOST: drone.example.com
      DRONE_SERVER_PROTO: https
      DRONE_TLS_CERT: /certs/drone.crt
      DRONE_TLS_KEY: /certs/drone.key
      DRONE_GITHUB_CLIENT_ID_FILE: /run/secrets/github_client_id
      DRONE_GITHUB_CLIENT_SECRET_FILE: /run/secrets/github_client_secret
      DRONE_ADMIN: your_github_username
    secrets:
      - github_client_id
      - github_client_secret
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

secrets:
  github_client_id:
    external: true
  github_client_secret:
    external: true
